spring:
  ai:
    proxy: # 需要改为自己的代理
      host: 127.0.0.1
      port: 1080
    openai:
      api-key: xxxx
#      base-url: https://one.aiskt.com
      chat:
        options:
          model: gpt-3.5-turbo

